## 100 Numpy Exercises

#### 1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.15.1


In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/john/anaconda_install/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/john/anaconda_install/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/john/anaconda_install/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/john/anaconda_install/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/john/anaconda_install/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/john/anaconda_install/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/john/anaconda_install/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/john/anaconda_install/ana

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to get the documentation of the numpy add function from the command line (★☆☆)

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 5. How to find the memory size of any array(★☆☆)

In [7]:
Z = np.zeros(10)
print("%d bytes" % (Z.size * Z.itemsize))

80 bytes


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
Z =  np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
Z = np.nonzero([1,2,0,0,4,0])
print(Z)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
Z =  np.random.random((3,3,3))
print(Z)

[[[0.19932047 0.45682155 0.20908612]
  [0.62203502 0.15433214 0.53149718]
  [0.14627265 0.75277071 0.84839526]]

 [[0.17793538 0.09589396 0.52610174]
  [0.75581796 0.15053382 0.46842172]
  [0.89515196 0.47609662 0.92914662]]

 [[0.82356287 0.37264869 0.22108758]
  [0.81195165 0.97563859 0.57727036]
  [0.36039077 0.63863104 0.2686123 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [28]:
Z = np.random.random((10,10))
Zmax, Zmin = Z.max(), Z.min()
print(Zmax, Zmin)

0.9904002033843726 0.016259235440714392


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5165639030466258


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [36]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [40]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width = 1, mode = 'constant', constant_values = 0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

In [41]:
print(0 * np.nan)

nan


In [42]:
print(np.nan == np.nan)

False


In [43]:
print(np.inf > np.nan)

False


In [44]:
print(np.nan - np.nan)

nan


In [45]:
print(np.nan in set([np.nan]))

True


In [46]:
print(0.3 == 3 * 0.1)

False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [52]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [69]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [71]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [76]:
Z = np.tile([(0,1), (1,0)], (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [77]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / np.std(Z)
print(Z)

[[ 0.79050779 -0.49569601  1.38885568  0.47658018 -1.33589615]
 [-0.7899831   1.20822649 -0.18191478 -0.78438323  0.32597261]
 [-0.76708784  0.21240514  1.52463561 -1.22914851  1.65280191]
 [-1.32442344 -1.31944775  0.1774782  -0.95034427  1.05977258]
 [-0.87420116 -1.04259729  1.55233622  0.55330381  0.17224731]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [4]:
# RGBA are red, blue, green and alpha
color = np.dtype([("r", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('b', 'u1'), ('g', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [2]:
# np.dot() is dot product of two arrays. 
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))

# If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.
Z = np.ones((5, 3)) @ np.ones((3, 2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
Z = np.arange(20)

Z[(3 <= Z) & (Z <= 8)] *=-1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)

In [4]:
# range(5) means creating an array from 0 to 4, sum(x, -1) means sum all elements in x, and then add -1
print(sum(range(5),-1))

9


In [8]:
# The difference between "import numpy" and "from numpy import *" is that for sum() in these two conditions, the sum()
# in the first condition will just be sum(), but in the second condition will be np.sum()

from numpy import *
print(sum(range(5), -1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [9]:
Z = np.arange(5)

# Z**Z means Z^Z
print(Z**Z)

[  1   1   4  27 256]


In [10]:
# N << Z means for each element x in Z, x = x * 2^N, Z >> N means for each element x in Z, x = x / 2^N
# "<<" means numpy.left_shift, ">>" means numpy.right_shift 
print(2 << Z >> 2)

[0 1 2 4 8]


In [12]:
# Z <- Z means numpy.less which returns the truth value of (x1 < x2) element-wise.
print(Z <- Z)

[False False False False False]


In [13]:
print(1j*Z)

[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]


In [14]:
print(Z/1/1)

[0. 1. 2. 3. 4.]


In [15]:
print(Z<Z>Z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

In [17]:
print(np.array(0) / np.array(0))

nan


/Users/john/anaconda_install/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [18]:
print(np.array(0) // np.array(0))

0


/Users/john/anaconda_install/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [22]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]
